/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  MyApp as MyApp
} from './components/my-app/my-app';

declare global {
  interface HTMLMyAppElement extends MyApp, HTMLElement {
  }
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-app": JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  TurnTouch as TurnTouch
} from './components/turn-touch/turn-touch';

declare global {
  interface HTMLTurnTouchElement extends TurnTouch, HTMLElement {
  }
  var HTMLTurnTouchElement: {
    prototype: HTMLTurnTouchElement;
    new (): HTMLTurnTouchElement;
  };
  interface HTMLElementTagNameMap {
    "turn-touch": HTMLTurnTouchElement;
  }
  interface ElementTagNameMap {
    "turn-touch": HTMLTurnTouchElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "turn-touch": JSXElements.TurnTouchAttributes;
    }
  }
  namespace JSXElements {
    export interface TurnTouchAttributes extends HTMLAttributes {
      
    }
  }
}

