/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  TurnTouch as TurnTouch
} from './components/turn-touch/turn-touch';

declare global {
  interface HTMLTurnTouchElement extends TurnTouch, HTMLElement {
  }
  var HTMLTurnTouchElement: {
    prototype: HTMLTurnTouchElement;
    new (): HTMLTurnTouchElement;
  };
  interface HTMLElementTagNameMap {
    "turn-touch": HTMLTurnTouchElement;
  }
  interface ElementTagNameMap {
    "turn-touch": HTMLTurnTouchElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "turn-touch": JSXElements.TurnTouchAttributes;
    }
  }
  namespace JSXElements {
    export interface TurnTouchAttributes extends HTMLAttributes {
      
    }
  }
}

